list: $/sfc/sfcsimple/models/event/columns.yaml
modelClass: Sfc\SfcSimple\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/events/update/:id'
