list: $/sfc/sfcsimple/models/ministry/columns.yaml
modelClass: Sfc\SfcSimple\Models\Ministry
title: Ministries
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/ministries/update/:id'
