list: $/sfc/sfcsimple/models/sermon/columns.yaml
modelClass: Sfc\SfcSimple\Models\Sermon
title: Sermons
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/sermons/update/:id'
