list: $/sfc/sfcsimple/models/update/columns.yaml
modelClass: Sfc\SfcSimple\Models\Update
title: Updates
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/updates/update/:id'
