list: $/sfc/sfcsimple/models/infopage/columns.yaml
modelClass: Sfc\SfcSimple\Models\Infopage
title: Infopages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/infopages/update/:id'
