list: $/sfc/sfcsimple/models/mleader/columns.yaml
modelClass: Sfc\SfcSimple\Models\Mleader
title: Mleaders
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/mleaders/update/:id'
