list: $/sfc/sfcsimple/models/leader/columns.yaml
modelClass: Sfc\SfcSimple\Models\Leader
title: Leader
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/leader/update/:id'
