list: $/sfc/sfcsimple/models/missionary/columns.yaml
modelClass: Sfc\SfcSimple\Models\Missionary
title: Missionary
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/missionary/update/:id'
