plugin:
    name: 'sfc.sfcsimple::lang.plugin.name'
    description: 'sfc.sfcsimple::lang.plugin.description'
    author: SFC
    icon: oc-icon-institution
    homepage: ''
permissions:
    sfc.events:
        tab: Events
        label: 'Full events access'
    sfc.infopage:
        tab: Pages
        label: 'Full pages access'
    sfc.sermon:
        tab: Sermons
        label: 'Full sermons access'
    sfc.update:
        tab: Update
        label: 'Full updates access'
    sfc.gallery:
        tab: Gallery
        label: 'Full gallery access'
    sfc.pro:
        tab: 'Pro Theme'
        label: 'Pro Theme Stuff'
    sfc.missionaries:
        tab: Missionaries
        label: 'Missionary Access (pro)'
navigation:
    events:
        label: Events
        url: sfc/sfcsimple/events
        icon: icon-calendar
        permissions:
            - sfc.events
        order: '3'
        sideMenu:
            event-submenu:
                label: Events
                url: sfc/sfcsimple/events
                icon: icon-calendar
                permissions:
                    - sfc.events
    sermons:
        label: Sermons
        url: sfc/sfcsimple/sermons
        icon: icon-microphone
        permissions:
            - sfc.sermon
        order: '2'
        sideMenu:
            sermons1:
                label: Sermons
                url: sfc/sfcsimple/sermons
                icon: icon-microphone
                permissions:
                    - sfc.sermon
            speakers:
                label: Speakers
                url: sfc/sfcsimple/speaker
                icon: icon-users
                permissions:
                    - sfc.sermon
            series:
                label: Series
                url: sfc/sfcsimple/series
                icon: icon-sitemap
                permissions:
                    - sfc.sermon
    infopages:
        label: Pages
        url: sfc/sfcsimple/infopages
        icon: icon-copy
        permissions:
            - sfc.infopage
        order: '5'
        sideMenu:
            pages-submenu:
                label: Pages
                url: sfc/sfcsimple/infopages
                icon: icon-copy
                permissions:
                    - sfc.infopage
            beliefs-submenu:
                label: Beliefs
                url: sfc/sfcsimple/beliefs
                icon: icon-book
                permissions:
                    - sfc.pro
            leaders-submenu:
                label: Leaders
                url: sfc/sfcsimple/leader
                icon: icon-users
                permissions:
                    - sfc.pro
    updates:
        label: Updates
        url: sfc/sfcsimple/updates
        icon: icon-bell
        permissions:
            - sfc.update
        order: '4'
        sideMenu:
            updates-submenu:
                label: Updates
                url: sfc/sfcsimple/updates
                icon: icon-bell
                permissions:
                    - sfc.update
    gallery:
        label: Galleries
        url: sfc/sfcsimple/galleries
        icon: icon-photo
        permissions:
            - sfc.gallery
        sideMenu:
            gallery-submenu:
                label: Galleries
                url: sfc/sfcsimple/galleries
                icon: icon-photo
                permissions:
                    - sfc.gallery
    ministries:
        label: Ministries
        url: sfc/sfcsimple/ministries
        icon: icon-group
        permissions:
            - sfc.pro
        sideMenu:
            ministries-submenu:
                label: Ministries
                url: sfc/sfcsimple/ministries
                icon: icon-sitemap
                permissions:
                    - sfc.pro
            leaders-submenu:
                label: 'Ministry Leaders'
                url: sfc/sfcsimple/mleaders
                icon: icon-user
                permissions:
                    - sfc.pro
    missionaries:
        label: Missionaries
        url: sfc/sfcsimple/missionary
        icon: icon-globe
        permissions:
            - sfc.missionaries
        sideMenu:
            missionary-submenu:
                label: Missionaries
                url: sfc/sfcsimple/missionary
                icon: icon-globe
                permissions:
                    - sfc.missionaries
