list: $/sfc/sfcsimple/models/belief/columns.yaml
modelClass: Sfc\SfcSimple\Models\Belief
title: Beliefs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sfc/sfcsimple/beliefs/update/:id'
